---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: src/index.html
  label: Home
- type: directory
  path: src/blog
  label: Blog
  create: documents
  match: "**/*"
- type: directory
  path: src/portfolio
  label: Portfolio
  create: documents
  match: "**/*"
  new_doc_ext: html
upload_dir: src/img
public_path: "/_site/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
